### ISSUE TITLE
trouble editting a problem

### ISSUE THREAD

**Issue by frrad** [clearloop/leetcode-cli#30]
when I try 1797 I get the following error:

```
leetcode edit 1797

[1797] Design Authentication Manager is on the run...


error: missing field `params` at line 61 column 1
```

I tried deleting / updating my cache hoping this would fix it but it seems not to. :/

**Comment by clearloop** [comment]
QAQ, are the problems except this 1797 can edit?

I'm quite busy these days, it would be nice if you're interested in contributing to this repo the bug is here:

https://github.com/clearloop/leetcode-cli/blob/dc19d2af697b6132479357d9b5fc7c4533211183/src/cache/models.rs#L169

Modify this line to `pub params: Option<Param>` and we will fix this

---

Or I will fix these two issues you mentioned this weekend, Thanks for trying leetcode-cli @frrad !!

**Comment by frrad** [comment]
Hey! Happy to take a stab at fixing these. Especially with your very clear suggestions. Would you mind approving the running of workflows for me? I have this message "First-time contributors need a maintainer to approve running workflows. Learn more." in https://github.com/clearloop/leetcode-cli/pull/31

Since I haven't used rust before I was hoping to just use your CI instead of figuring out how to set up a local dev environment haha

**Comment by clearloop** [comment]
> Would you mind approving the running of workflows for me?

Approved, glad to see that~ If you are confused with any code of this repo, feel free to ping me
